project:
  type: website
  title: "posit-blogs"
  render:
    - markdown-blogs/*/index.md
    - markdown-blogs/*/index.Rmd
    - markdown-blogs/*/index.qmd
  output-dir: public

format:
  html:
    theme: none

execute:
  freeze: auto
