name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, survival=?ignore-before-r=3.5.0
          needs: check
      - run: |
           sudo apt install python3-pip python3-dev;
           pip install jupyter; pip install numpy; pip install matplotlib
           quarto create-project myproject
           cd myproject; rm _quarto.yml
           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
           quarto render --to html   
           echo show files 
           tree /home/runner/work/quatrotest/quatrotest/myproject






          
     #      sudo apt update; sudo apt -s upgrade
     #      sudo apt upgrade r-base r-base-dev
     #      sudo apt install python3-pip python3-dev;

     
#          sudo apt-get install pandoc
#          sudo apt-get install texlive
#          echo INSTALLING R PACKAGES
#          R CMD INSTALL install.packages(“tinytex”)
#          R CMD INSTALL install.packages(“rmarkdown”)  
  




# Good for .md and .qmd
#      - run: |
#           sudo apt install python3-pip python3-dev;
#           pip install jupyter; pip install numpy; pip install matplotlib
#           quarto create-project myproject
#           cd myproject; rm _quarto.yml
#           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
#           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
#           quarto render --to html   
#           echo show files 
#           tree /home/runner/work/quatrotest/quatrotest/myproject










