name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto --version
          pwd
          ls -l
          quarto render markdown/index.md --to html


      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "/home/runner/work/quatrotest/quatrotest/"
          target: "/output"



