name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
           sudo apt update; sudo apt -s upgrade
           echo UPGRADING R-BASE-CORE
           sudo apt upgrade r-base r-base-dev
           echo R BASE CORE UPGRADE COMPLETE
           sudo apt install python3-pip python3-dev;
           pip install jupyter; pip install numpy; pip install matplotlib
           echo INSTALLING RAPI3.4
           sudo add-apt-repository ppa:marutter/c2d4u3.5
           sudo apt-get update
           sudo apt-get install r-api-3.5
           echo INSTALLING RAPI3.4 COMPLETE
           echo INSTALL JSONLITE
           sudo apt-get install -y r-cran-jsonlite
           echo JSONLITE INSTALLATION COMPLETE
           quarto create-project myproject
           cd myproject; rm _quarto.yml
           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
           quarto render --to html   
     
  
  
  











