name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r-dependencies@v1
      - name: Install dependencies  
        run: |
          ## Installing/Updating packages
          export R_LIBS='/home/runner/work/quatrotest/quatrotest/renv/library/'
          cat("::group::Installing/updating packages\n")
          Sys.setenv("PKGCACHE_HTTP_VERSION" = "2")
          pak::lockfile_install(".github/pkg.lock")
          cat("::endgroup::\n")
          cat("::group::Session info\n")
          if (requireNamespace("sessioninfo", quietly = TRUE)) {
            if (packageVersion("sessioninfo") >= "1.2.1") {
              sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
            } else {
              options(width = 200)
              sessioninfo::session_info(rownames(installed.packages()), include_base=TRUE)
            }
          } else {
            sessionInfo()
          }
          ## Clean up lock file
          unlink(".github/pkg.lock")
          cat("::endgroup::\n")
        shell: Rscript {0}
        working-directory: /home/runner/work/quatrotest/quatrotest/renv/library/R-4.2/x86_64-pc-linux-gnu
     
     
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html      
     
     #  default: ~/work/quatrotest/quatrotest
     
           
    #     R remotes::install_deps(dependencies = TRUE)
    #     shell: Rscript {0}
    
    #     sudo apt-get update
    #     sudo apt-get install -f r-base
    #     sudo apt-get install r-base-core
    #     wget https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+
    #     R -e \\install.packages("rmarkdown", repos = "https://cran.revolutionanalytics.com")
         
         
  #         sudo apt-get install r-cran-markdown       
  #         sudo apt-get install cmake
  #         install.packages("rmarkdown")
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
             



#            python3 -m pip install jupyter matplotlib plotly_express



#      - uses: r-lib/actions/setup-pandoc@v1
#      - uses: r-lib/actions/setup-r@v1
#      - uses: r-lib/actions/setup-renv@v1
