name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
           Remotes: rstudio/rmarkdown@70b9f1ec4ce71628d
  #         install.packages("rmarkdown")
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
             



#            python3 -m pip install jupyter matplotlib plotly_express
