name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
         echo show sources list
         cat  /etc/apt/sources.list      
         echo after adding entry
         echo "/etc/apt/sources.list">/etc/apt/sources.list
           
    # sudo apt-get install cmake
    # sudo apt-get install r-base-core 3.6.3-2
    # sudo apt-get install r-api-3.5
           
           
  # sudo apt-get install r-cran-markdown
  #         install.packages("rmarkdown")
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
             



#            python3 -m pip install jupyter matplotlib plotly_express
