name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          sudo apt-get update
          sudo apt-get install python3.6; wget https://bootstrap.pypa.io/get-pip.py; sudo /usr/bin/python get-pip.py
          pip install jupyter_nbextensions_configurator
          git clone https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git; pip install -e jupyter_contrib_nbextensions
          jupyter contrib nbextension install --user
          echo Jupyter installation complete
          quarto create-project myproject
          cd myproject; rm _quarto.yml
          mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
          mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
          quarto render --to html




   
     ##   sudo /usr/bin/python -m pip install ipykernel jupyter jupyter_cms ipython jupyter_nbextensions_configurato
     ##   jupyter nbextensions_configurator enable --user 







