name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
           sudo dpkg -i $DEB
           tar xvzf $TGZ --strip-components 1 -C ~/pandoc
           ar p $DEB data.tar.gz | tar xvz --strip-components 2  ~/pandoc
  #         install.packages("rmarkdown")
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
             



#            python3 -m pip install jupyter matplotlib plotly_express
