name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-tinytex@master
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "sysreqs::sysreq_commands('DESCRIPTION')")
          sudo apt-get update
          sudo eval "$sysreqs"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"




      
      
      
      
      





  




# Good for .md and .qmd
#      - run: |
#           sudo apt install python3-pip python3-dev;
#           pip install jupyter; pip install numpy; pip install matplotlib
#           quarto create-project myproject
#           cd myproject; rm _quarto.yml
#           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
#           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
#           quarto render --to html   
#           echo show files 
#           tree /home/runner/work/quatrotest/quatrotest/myproject










