name: quarto-setup

on: 
  push:
    branches: none

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    container: jpgomezz/quarto:final            
    steps:
     - uses: actions/checkout@v1
       name: Render files
     - run: |
          sudo apt-get update
          sudo apt-get install tree
          echo STARTING WITH THE PROJECT
          cd /__w/quarto-actions/quarto-actions/
          quarto render --to html
          tree public/markdown/
     - uses: actions/upload-artifact@master
       with:
        name: my-artifact
        path: public/markdown/


  sftp-transfer:
    needs: quarto-linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository content
        uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
         name: my-artifact
         path: public/markdown/
     
      - run: | 
          echo CHECKING ARTIFACT
          ls -la /home/runner/work/quarto-actions/quarto-actions/public/markdown/
     
      - run: |
          mkdir -p ${{ secrets.SSH_PATH }}
          touch /home/runner/.ssh/known_hosts
          touch ${{ secrets.SSH_CONFIG_PATH }}
          echo "${{ secrets.SSH_CONFIG }}" >> ${{ secrets.SSH_CONFIG_PATH }}
          echo "${{ secrets.PRIVATEKEY }}" > "/home/runner/.ssh/id_rsa"    
          echo "${{ secrets.PUBLICKEY }}" > "/home/runner/.ssh/id_rsa.pub"      
          echo "${{ secrets.KNOWN_HOSTS }}" > "/home/runner/.ssh/known_hosts"
          chmod 700 "/home/runner/.ssh/"
          chmod 644 "/home/runner/.ssh/known_hosts"
          chmod 600 "/home/runner/.ssh/id_rsa"
          chmod 644 "/home/runner/.ssh/id_rsa.pub"
          chmod 600 "/home/runner/.ssh/config"
          sftp -oPort=2222 dev.6ea2702b-ed4d-4196-b545-10c1de13b528@appserver.dev.6ea2702b-ed4d-4196-b545-10c1de13b528.drush.in <<END
          put -r /home/runner/work/quarto-actions/quarto-actions/public/markdown/* /files/
          
          
          
          
