name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y r-cran-jsonlite
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
          sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'





# Good for .md and .qmd
 #      - run: |
 #           sudo apt install python3-pip python3-dev;
 #           pip install jupyter; pip install numpy; pip install matplotlib
 #           quarto create-project myproject
 #           cd myproject; rm _quarto.yml
 #           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
 #           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
 #           quarto render --to html   
 #           echo show files 
 #           tree /home/runner/work/quatrotest/quatrotest/myproject



#Good for now R is able to install some packages
  #        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
  #        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
  #        sudo apt install r-base
  #        R --version
  #        sudo R --vanilla <<EOF
  #        install.packages("tinytex")
  #        q()
  #        EOF


# Good for R interface usage
     #     R --version
     #     sudo R --vanilla <<EOF
     #     install.packages("rmarkdown")
     #     q()
     #     EOF


