name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., local::./tests/testthat/testpkg




      
      
      
      
      











  




# Good for .md and .qmd
#      - run: |
#           sudo apt install python3-pip python3-dev;
#           pip install jupyter; pip install numpy; pip install matplotlib
#           quarto create-project myproject
#           cd myproject; rm _quarto.yml
#           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
#           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
#           quarto render --to html   
#           echo show files 
#           tree /home/runner/work/quatrotest/quatrotest/myproject










