name: quarto-setup

on: 
  push:
    branches: jp-test

#jobs:
#  quarto-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: quarto-dev/quarto-actions/setup@v2
#      - run: |
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
           
jobs:
  render_document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: markdown/hello.qmd
          run: |
             echo print working directory
             ls -l
             




