name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          echo show files
          ls -l
          quarto create-project myproject
          echo list files after creating proyect
          ls -l
          echo files inside of myproject
          cd myproject
          rm _quarto.yml
          ln -sf /home/runner/work/quatrotest/quatrotest/_quarto.yml /home/runner/work/quatrotest/quatrotest/myproject/_quarto.yml
          ls -l
          cat _quarto.yml

#          echo crating symbolic link
#          ln -sf _quarto.yml /home/runner/work/quatrotest/quatrotest/myproject/_quarto.yml

#      - name: Render Quarto Project
#        uses: quarto-dev/quarto-actions/render@v2
#        with:
#          to: html # If set, it will be equivalent to `quarto render --to html`
#          path: myproject # By default, the current working dir is used i.e `quarto render .`




