name: quarto-setup

on: 
  push:
    branches: jp-test

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarto-dev/quarto-actions/setup@v2
      - run: |
           quarto create-project myproject
           cd myproject; rm _quarto.yml
           mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
           mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
           quarto render --to html      
     
  
  
  
  #  default: ~/work/quatrotest/quatrotest
     
           
    #     R remotes::install_deps(dependencies = TRUE)
    #     shell: Rscript {0}
    
    #     sudo apt-get update
    #     sudo apt-get install -f r-base
    #     sudo apt-get install r-base-core
    #     wget https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+
    #     R -e \\install.packages("rmarkdown", repos = "https://cran.revolutionanalytics.com")
         
         
  #         sudo apt-get install r-cran-markdown       
  #         sudo apt-get install cmake
  #         install.packages("rmarkdown")
  #         quarto create-project myproject
  #         cd myproject; rm _quarto.yml
  #         mv ~/work/quatrotest/quatrotest/_quarto.yml ~/work/quatrotest/quatrotest/myproject/_quarto.yml
  #         mv ~/work/quatrotest/quatrotest/markdown ~/work/quatrotest/quatrotest/myproject/markdown
  #         quarto render --to html
